# 基础镜像
FROM alpine

# 作者
MAINTAINER small

# 修改源
RUN ["sed","-i","s/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g","/etc/apk/repositories"]
RUN apk update

# 安装nginx
RUN apk add nginx && mkdir /run/nginx/


# 设置环境变量
ENV PATH /usr/local/nginx/sbin:$PATH

EXPOSE 80 443 22

CMD ["nginx"]

# 容器启动后，执行命令
ENTRYPOINT ["nginx","-g","daemon off;"]
